CREATE SEQUENCE ORDER_SEQUENCE INCREMENT 1 START 1000;

CREATE TABLE PRODUCT_ORDER (
  ID int8 PRIMARY KEY NOT NULL DEFAULT nextval('ORDERS.ORDER_SEQUENCE'),
  ADDRESS VARCHAR (50) NOT NULL,
  PRODUCT VARCHAR (256) NOT NULL
);